### ISSUE TITLE
Creating TAP/TUN devices with custom names

### ISSUE THREAD

**Issue by mdlayher** [pkg/taptun#6]
Hello!  I'd like to add a patch to allow custom names for TAP/TUN devices created with this package.  I already have it working on Linux, but I'm unsure if it's even possible on BSD.

Do you have any ideas, @ebfe ?

For the API, I was thinking something along the lines of: `func NewTap(name string) (*Tap, error)`.  The existing `OpenTap()` function would just invoke `NewTap("")`.

Would you accept a PR for this functionality, @davecheney ?

Thanks for your time.

EDIT: my initial work-in-progress commit is here: https://github.com/mdlayher/taptun/commit/fb1ed47abe90a671166ad22f60383705ed5daa69.

**Comment by ebfe** [comment]
On FreeBSD the SIOCSIFNAME ioctl should work. I don't think it's possible to rename interfaces on OpenBSD.

**Comment by mdlayher** [comment]
Tried out an initial stab at FreeBSD support: https://github.com/mdlayher/taptun/blob/d029227a1bf45c337c1a864ebb20874969dbcd16/taptun_freebsd.go

Running this program on a FreeBSD VM tells me "inappropriate ioctl for device", which I assume is the result of the rename.  Any ideas, @ebfe ?

**Comment by mdlayher** [comment]
A coworker has pointed me to here: https://svnweb.freebsd.org/base/head/sbin/ifconfig/ifconfig.c?revision=281143&view=markup#l1012

Looks like `ifreq` has a union in it which we may need to populate correctly to make this work.  I'm not sure what the best course of action is at this point.

**Comment by ebfe** [comment]
I think the ioctl works on sockets not the tun/tap fd, so you have to open a dummy socket to use.
ifreq.ifr_name is the old interface name ifreq.ifr_data a pointer to the new name.

**Comment by ebfe** [comment]
@mdlayher https://gist.github.com/ebfe/75ae79a267ab4724c903

**Comment by davecheney** [comment]
@ebfe @mdlayher sure, sounds like a good improvement.

**Comment by mdlayher** [comment]
Excellent.  I should have something put together in the near future.  Thanks again for this package.  It's being put to good use at DigitalOcean!

**Comment by mdlayher** [comment]
Pull request created: https://github.com/pkg/taptun/pull/7

**Comment by davecheney** [comment]
Closed in #7
